services:
  database:
    env_file:
      - .env
    build:
      context: .
      dockerfile: db/Dockerfile
    volumes:
      - ./data:/data
     
  analysis:
    env_file:
      - .env
    build:
      context: .
      dockerfile: analysis/Dockerfile
    volumes:
      - ./data:/data
      - ./analysis/queries:/home/jovyan/work/queries
      - ./analysis/notebooks:/home/jovyan/work/notebooks
      - ./analysis/graphs:/home/jovyan/work/graphs
    ports:
      - 8888:8888